src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Repository\EntrepriseRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EntrepriseRepository::class)]

class Entreprise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_entreprise = null;

    #[ORM\Column(length: 9)]
    private ?string $siren = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(length: 5)]
    private ?string $codepostal = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $gerant = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ville = null;

    #[ORM\Column(length: 16, nullable: true)]
    private ?string $tel1 = null;

    #[ORM\Column(length: 16, nullable: true)]
    private ?string $tel2 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $mail_principal = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $mail_secondaire = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $mail_annonces_occasions = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEntreprise(): ?string
    {
        return $this->nom_entreprise;
    }

    public function setNomEntreprise(string $nom_entreprise): self
    {
        $this->nom_entreprise = $nom_entreprise;

        return $this;
    }

    public function getsiren(): ?string
    {
        return $this->siren;
    }

    public function setsiren(string $siren): self
    {
        $this->siren = $siren;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodepostal(): ?string
    {
        return $this->codepostal;
    }

    public function setCodepostal(string $codepostal): self
    {
        $this->codepostal = $codepostal;

        return $this;
    }

    public function getGerant(): ?string
    {
        return $this->gerant;
    }

    public function setGerant(?string $gerant): self
    {
        $this->gerant = $gerant;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getTel1(): ?string
    {
        return $this->tel1;
    }

    public function setTel1(?string $tel1): self
    {
        $this->tel1 = $tel1;

        return $this;
    }

    public function getTel2(): ?string
    {
        return $this->tel2;
    }

    public function setTel2(?string $tel2): self
    {
        $this->tel2 = $tel2;

        return $this;
    }

    public function getMailprincipal(): ?string
    {
        return $this->mail_principal;
    }

    public function setMailprincipal(?string $mailprincipal): self
    {
        $this->mail_principal = $mailprincipal;

        return $this;
    }

    public function getMailsecondaire(): ?string
    {
        return $this->mail_secondaire;
    }

    public function setMailsecondaire(?string $mailsecondaire): self
    {
        $this->mail_secondaire = $mailsecondaire;

        return $this;
    }

    public function getMailAnnoncesOccasions(): ?string
    {
        return $this->mail_annonces_occasions;
    }

    public function setMailAnnoncesOccasions(?string $mail_annonces_occasions): self
    {
        $this->mail_annonces_occasions = $mail_annonces_occasions;

        return $this;
    }
}

src/Entity/Services.php
<?php

namespace App\Entity;

use App\Repository\ServicesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: ServicesRepository::class)]
#[UniqueEntity('nom',"Il existe déjà un service portant ce nom dans la base, veuillez rectifier le nom svp.")]    

class Services
{ 
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT, nullable: false)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?float $prix_a_partir_de = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $icone = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    private ?string $resume = null;

    #[ORM\OneToMany(mappedBy: 'service', targetEntity: Telephones::class)]
    private Collection $telephones;

    #[ORM\OneToMany(mappedBy: 'service', targetEntity: Mails::class)]
    private Collection $mails;

    #[ORM\Column(length: 16, nullable: true)]
    private ?string $telephone_1 = null;

    #[ORM\Column(length: 16, nullable: true)]
    private ?string $telephone_2 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $responsable = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $mail_service_1 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $mail_service_2 = null;

    #[ORM\Column]
    private ?bool $afficher = null;

    #[ORM\Column(length: 15, nullable: true)]
    private ?string $civilite_responsable = null;

    public function __toString()
    {
        return $this->nom;
    }

    public function __construct()
    {
        $this->telephones = new ArrayCollection();
        $this->mails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrixAPartirDe(): ?float
    {
        return $this->prix_a_partir_de;
    }

    public function setPrixAPartirDe(?float $prix_a_partir_de): self
    {
        $this->prix_a_partir_de = $prix_a_partir_de;

        return $this;
    }

    public function getIcone(): ?string
    {
        return $this->icone;
    }

    public function setIcone(?string $icone): self
    {
        $this->icone = $icone;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(string $resume): self
    {
        $this->resume = $resume;

        return $this;
    }

    /**
     * @return Collection<int, Telephones>
     */
    public function getTelephones(): Collection
    {
        return $this->telephones;
    }

    public function addTelephone(Telephones $telephone): self
    {
        if (!$this->telephones->contains($telephone)) {
            $this->telephones->add($telephone);
            $telephone->setService($this);
        }

        return $this;
    }

    public function removeTelephone(Telephones $telephone): self
    {
        if ($this->telephones->removeElement($telephone)) {
            // set the owning side to null (unless already changed)
            if ($telephone->getService() === $this) {
                $telephone->setService(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Mails>
     */
    public function getMails(): Collection
    {
        return $this->mails;
    }

    public function addMail(Mails $mail): self
    {
        if (!$this->mails->contains($mail)) {
            $this->mails->add($mail);
            $mail->setService($this);
        }

        return $this;
    }

    public function removeMail(Mails $mail): self
    {
        if ($this->mails->removeElement($mail)) {
            // set the owning side to null (unless already changed)
            if ($mail->getService() === $this) {
                $mail->setService(null);
            }
        }

        return $this;
    }

    public function getTelephone1(): ?string
    {
        return $this->telephone_1;
    }

    public function setTelephone1(?string $telephone_1): self
    {
        $this->telephone_1 = $telephone_1;

        return $this;
    }

    public function getTelephone2(): ?string
    {
        return $this->telephone_2;
    }

    public function setTelephone2(?string $telephone_2): self
    {
        $this->telephone_2 = $telephone_2;

        return $this;
    }

    public function getResponsable(): ?string
    {
        return $this->responsable;
    }

    public function setResponsable(?string $responsable): self
    {
        $this->responsable = $responsable;

        return $this;
    }

    public function getMailService1(): ?string
    {
        return $this->mail_service_1;
    }

    public function setMailService1(?string $mail_service_1): self
    {
        $this->mail_service_1 = $mail_service_1;

        return $this;
    }

    public function getMailService2(): ?string
    {
        return $this->mail_service_2;
    }

    public function setMailService2(?string $mail_service_2): self
    {
        $this->mail_service_2 = $mail_service_2;

        return $this;
    }

    public function isAfficher(): ?bool
    {
        return $this->afficher;
    }

    public function setAfficher(bool $afficher): self
    {
        $this->afficher = $afficher;

        return $this;
    }

    public function getCiviliteResponsable(): ?string
    {
        return $this->civilite_responsable;
    }

    public function setCiviliteResponsable(?string $civilite_responsable): self
    {
        $this->civilite_responsable = $civilite_responsable;

        return $this;
    }
}

src/Entity/Utilisateurs.php
<?php

namespace App\Entity;

use App\Repository\UtilisateursRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UtilisateursRepository::class)]
class Utilisateurs
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $nom = null;

    #[ORM\Column(length: 100)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    #[ORM\Column]
    private ?bool $is_verified = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\OneToMany(mappedBy: 'utilisateur', targetEntity: Mails::class)]
    private Collection $mails;

    public function __construct()
    {
        $this->mails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getRoles(): array
    {
        return $this->roles;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function isIsVerified(): ?bool
    {
        return $this->is_verified;
    }

    public function setIsVerified(bool $is_verified): self
    {
        $this->is_verified = $is_verified;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Mails>
     */
    public function getMails(): Collection
    {
        return $this->mails;
    }

    public function addMail(Mails $mail): self
    {
        if (!$this->mails->contains($mail)) {
            $this->mails->add($mail);
            $mail->setUtilisateur($this);
        }

        return $this;
    }

    public function removeMail(Mails $mail): self
    {
        if ($this->mails->removeElement($mail)) {
            // set the owning side to null (unless already changed)
            if ($mail->getUtilisateur() === $this) {
                $mail->setUtilisateur(null);
            }
        }

        return $this;
    }
}

templates/_partials/_admin-nav.html.twig
<aside class="menu-lateral-gauche">
	<div class="menu-options">
		{% if is_granted("ROLE_ADMIN") %}
			<div class="menu-item">
				<div class="menu-title">Données entreprise</div>
				<p>
					<a class="menu-link" href="{{path('fiche_entreprise')}}">Fiche entreprise</a>
				</p>
			</div>
			<div class="menu-item">
				<div class="menu-title">Gestion accueil</div>
				<p>
					<a class="menu-link" href="{{path('fiche_homepage')}}">Page d'accueil</a>
				</p>

			</div>

			<div class="menu-item">
				<div class="menu-title">Clients</div>
				<p>
					<a class="menu-link" href="{{path('app_clients_liste_clients')}}">Liste clients</a>
				</p>
				<p>
					<a class="menu-link" href="{{path('app_clients_creer_client')}}">+ Ajouter client</a>
				</p>
			</div>
			<div class="menu-item">
				<div class="menu-title">Utilisateurs</div>
				<p>
					<a class="menu-link" href="{{path('app_utilisateurs_liste_utilisateurs')}}">Liste utilisateurs</a>
				</p>
				<p>
					<a class="menu-link" href="{{path('app_utilisateurs_creer_utilisateur')}}">+ Ajouter utilisateur</a>
				</p>
			</div>
		{% endif %}

		{% if is_granted("ROLE_EMPLOYEE")  %}

			<div class="menu-item">
				<div class="menu-title">Véhicules</div>
				<p>
					<a class="menu-link" href="{{path('app_vehicules_liste_vehicules')}}">Liste véhicules</a>
				</p>
				<p>
					<a class="menu-link" href="{{path('app_vehicules_creer_vehicule')}}">+ Ajouter véhicule</a>
				</p>
				<p>
					<a class="menu-link" href="{{path('app_marques_liste_marques')}}">Liste marques</a>

				</p>
				<p>
					<a class="menu-link" href="{{path('app_marques_creer_marque')}}">+ Ajouter marque</a>
				</p>
				<p>
					<a class="menu-link" href="{{path('app_motorisations_liste_motorisations')}}">Liste motorisations</a>

				</p>
				<p>
					<a class="menu-link" href="{{path('app_motorisations_creer_motorisation')}}">+ Ajouter motorisation</a>
				</p>
				<p>
					<a class="menu-link" href="{{path('app_boites_liste_boites')}}">Liste boites</a>

				</p>
				<p>
					<a class="menu-link" href="{{path('app_boites_creer_boite')}}">+ Ajouter boîte</a>
				</p>
				<p>
					<a class="menu-link" href="{{path('app_vehicules_types_vehicules_index')}}">Liste types véhicules</a>
				</p>
				<p>
					<a class="menu-link" href="{{path('app_vehicules_types_vehicules_creer')}}">+ Ajouter type véhicule</a>
				</p>

			</div>
			<div class="menu-item">
				<div class="menu-title">Commentaires</div>
				<p>
					<a href="{{path('app_commentaires_liste_commentaires')}}" class="menu-link">Liste commentaires</a>
				</p>
				<p>
					<a href="{{path('creer_commentaire')}}" class="menu-link">+ Ajouter commentaire</a>
				</p>
			</div>
			<div class="menu-item">
				<div class="menu-title">Services</div>
				<p>
					<a href="{{path('liste_services')}}" class="menu-link">Liste services</a>
				</p>
				<p>
					<a href="{{path('app_services_creer_service')}}" class="menu-link">+ Ajouter service</a>
				</p>
			</div>
		{% endif %}
	</div>
</aside>

templates/_partials/_comments.html.twig
{# Formulaire des commentaires #}
<div class="container-commentaires">
	<h2>Liste des commentaires</h2>
	<div class="liste-commentaires">
		<div class="wrapper-commentaire">
			{% for c in commentaires %}
				{% if c.parent == null %}
					<div class="contenu-commentaire">
						<div class="entete-commentaire">

							<p class="publication-par">Publié par
								<strong>{{c.pseudo}}</strong>
								<span>le
									{{c.createdAt|date("d-m-Y à H:i:s")}}</span>
							</p>
						</div>
						<div class="texte-commentaire">{{c.contenu|raw}}</div>
						<p>
							<a class="btn-repondre" href="#ajout-commentaire" data-reply data-id="{{c.id}}">
								<i class="fa-solid fa-reply"></i>Répondre</a>
						</p>
					</div>
					{# Affichage des réponses #}
					{% for reponse in c.reponses %}
						<div class="reponse">
							<p>Réponse publiée par
								{{reponse.pseudo}}
								le
								{{reponse.createdAt|date("d-m-Y à H:i:s")}}</p>
							<div class="contenu-reponse">
								--
								{{reponse.contenu|raw}}
								<p>
								{% endfor %}
							{% endif %}
						{% endfor %}
					</div>
				</div>
			</div>
			{{ form_start(commentForm)}}
			<div class="form-header">Ajouter un commentaire</div>
			<div class="container-etoiles">
				<p class="text-note">Votre note :
				</p>
				<i class="fa-regular fa-star etoile" data-value="1"></i>
				<i class="fa-regular fa-star etoile" data-value="2"></i>
				<i class="fa-regular fa-star etoile" data-value="3"></i>
				<i class="fa-regular fa-star etoile" data-value="4"></i>
				<i class="fa-regular fa-star etoile" data-value="5"></i>
				<i class="fa-regular fa-star etoile" data-value="6"></i>
				<i class="fa-regular fa-star etoile" data-value="7"></i>
				<i class="fa-regular fa-star etoile" data-value="8"></i>
				<i class="fa-regular fa-star etoile" data-value="9"></i>
				<i class="fa-regular fa-star etoile" data-value="10"></i>
			</div>

			{{ form_row(commentForm.note)}}
			{{ form_row(commentForm.email)}}
			{{ form_row(commentForm.pseudo)}}
			{{ form_row(commentForm.contenu)}}
			{{ form_row(commentForm.rgpd)}}
			<p class="alerte-publication-commentaire">Un commentaire ne sera publié qu'après acceptation de la part de nos modérateurs.Vous ne le verrez donc pas forcément immédiatement sur cette section...</p>
			{{ form_end(commentForm)}}
		</div>
	</div>
</div>
{% block javascripts %}
	<script type="text/javascript" src="{{asset('assets/js/commentaires.js')}}" defer></script>
	<script type="text/javascript" src="{{asset('assets/js/ckeditor.js')}}" defer></script>
	<script src="{{asset('assets/js/notation.js')}}" type="text/javascript" defer></script>
{% endblock %}

templates/_partials/_cookies.html.twig
<!--Banner cookies-->
<div class="cookies-banner-fr hidden">

	<div>
		<img class="img-cookie box-shadow" src="{{asset('assets/uploads/img/cookies.jpg')}}" alt="Image de cookie sur clavier de pc portable">
	</div>
	<div class="cookies-text-container">
		<h1>Gestion des cookies</h1>
		<p>Notre site utilise des cookies visant à améliorer l'expérience utilisateur en
													                        enregistrant le
													                        minimum d'information concernant votre navigation.
		</p>
		<p>
			L'acceptation des cookies permet de vous présenter des publicités pertinentes et d'améliorer votre expérience de navigation tout en préservant au maximum votre privacité...
		</p>
		<p>Notre entreprise n'utilisera et ne diffusera jamais vos informations personnelles.</p>

		<p>
			Pour en savoir plus ou personnaliser vos préférences de cookies cliquez sur le bouton
													                        "préférences"</p>


	</div>
	<div class="boutons-cookies">
		<button class="btn accept-cookies btn-success" type="button">Accepter</button>
		<button class="btn preferences-cookies btn-warning" type="button">Preferences...</button>
		<button class="btn decline-cookies btn-danger" type="button">Refuser</button>
	</div>

</div>

templates/_partials/_creneauxJour.html.twig
<div class="horaires-du-jour">
	<p>Horaires du jour :</p>
	{# Si aucun créneau disponible pour le jour actuel alors message d'alerte de fermeture #}
	{% if(creneauxActifsJour is empty and prochainsCreneaux is empty)%}
		<p class="alert-danger">Fermé aujourd'hui</p>

	{% else %}

		{# Affiche le créneau par rapport à l'heure actuelle #}

		{% if(creneauxActifsJour is not empty)%}
			{% for creneau in creneauxActifsJour %}

				<p>Ferme à
					{{creneau.fin|date("H:i")}}</p>

			{% endfor %}
		{% else %}
			<p class="badge-danger">Fermé en ce moment</p>
		{% endif %}

		{# Affiche les prochains créneaux pour le jour actuel #}
		{% if (prochainsCreneaux is not empty) %}
				<p>Ouvrira : </p>
				{% for creneau in prochainsCreneaux %}
			<p class="prochain-creneau-jour">
					De
					{{creneau.debut|date("H:i")}} 
					à
					{{creneau.fin|date("H:i")}}
					</p>
			{% endfor %}
		{% endif %}

	{% endif %}

	<a class="link-horaires-semaine" href="{{path('app_horaires_semaine_index')}}">Voir horaires semaine</a>
</div>

templates/_partials/_derniers-vehicules.html.twig
{% for vehicule in vehicules %}
	<table>
		<tbody>
			<tr>
				<td>
					{# Gestion des photos #}
					{% if vehicule.photos[0] is defined %}
						<a href="{{path('app_vehicules_annonces_details_vehicule',{id:vehicule.id})}}"><img class="mini-thumbnail" src="{{asset('assets/uploads/vehicules/mini/300x300-'~ vehicule.photos[0].nom)}}" alt="{{vehicule.photos[0].nom}}"></a>
					{% endif %}
				</td>
				<td>
					<strong>{{vehicule.marque}}</strong>
				</td>
				<td>{{vehicule.modele}}</td>
				<td>{{vehicule.prixvente}}
					€</td>
				<td>
					<a class="btn btn-primary" href="{{path('app_vehicules_annonces_details_vehicule',{id:vehicule.id})}}"><i class="fa-regular fa-eye"></i>Fiche</a>
				</td>
			</tr>
		</tbody>
	</table>
{% endfor %}

templates/_partials/_footer.html.twig
<footer>
	
	{{render(controller('App\\Controller\\CreneauxController::afficherCreneauJourActif'))}}

</footer>

templates/_partials/_galerie-photos.html.twig
{# Galerie photos #}
<div class="wrapper-galerie-photos">
	<div class="galerie-photos">
		{% if vehicule.photos is defined %}
			{% for photo in vehicule.photos %}
				<div class="container-thumbnail">
					<img class="thumbnail-vehicule" src="{{asset('assets/uploads/vehicules/mini/300x300-'~ photo.nom)}}" alt="">
					{% if is_granted("ROLE_ADMIN") %}
						<a class="btn-suppression-photo" href="{{path('app_vehicules_supprimer_photo',{id:photo.id})}}" data-delete data-token="{{csrf_token('delete' ~ photo.id)}}">&times;</a>
					{% endif %}
				</div>
			{% endfor %}
		{% endif %}
	</div>
</div>
{% block javascripts %}
	<script src="{{asset('assets/js/photos.js')}}" type="text/javascript" defer></script>
{% endblock %}

templates/_partials/_header.html.twig
<header>
	{% if homepage.logo is not null %}
		<div class="entreprise">
			<a class="logo-entreprise" href="#" class="navbar-brand" aria-label="Logo"><img src="{{asset('assets/uploads/logo/' ~ homepage.logo)}}" alt="Logo entreprise" style="height:50px;"></a>
			<h1 class="nom-entreprise">{{entreprise.nomEntreprise}}</h1>
		</div>
	{% else %}
		<div class="entreprise">
			<i class="fa-solid fa-truck-pickup icone-entreprise"></i>
			<h1 class="nom-entreprise">{{entreprise.nomEntreprise}}</h1>
		</div>
	{% endif %}

	{% if entreprise.tel1 is not null %}
		<div class="telephone">
			<i class="fa-solid fa-phone icone-telephone"></i>
			<a class="telephone-entreprise" href="tel:" {{entreprise.tel1}}>{{entreprise.tel1}}</a>
		</div>
	{% endif %}
</header>

templates/_partials/_modal.html.twig
<div id="myModal" class="modal">

	<div class="modal-content">
		<div class="modal-header">
			<span class="close">&times;</span>
			<h2>Modal Header</h2>
		</div>
		<div class="modal-body">

		</div>
		<div class="modal-footer">
			<h3>Modal Footer</h3>
		</div>
	</div>
</div>
{% block javascripts %}
	<script src="{{asset('assets/js/modal.js')}}" type="text/javascript" defer></script>
{% endblock %}

templates/_partials/_modale-contact.html.twig
{% extends 'base.html.twig' %}
{% block body %}
	<main>
		<div class="modal" id="modale-contact">
			<div class="modal-header"></div>
			<div class="divider"></div>

			<div class="modal-content">
				{{form_start(form)}}
				<div class="form-header">Contacter le service
					{{nomService}}
				</div>
				{{form_row(form.subject)}}
				{{form_row(form.email)}}
				{{form_row(form.telContact)}}
				{{form_row(form.message)}}

				<button type="submit" class="btn btn-primary btn-centered">Envoyer</button>
			</div>
			{{form_end(form)}}
			<div class="divider"></div>
			<div
				class="modal-footer">{# <button class="btn btn-secondary btn-right modal-trigger" data-target="modale-contact">Fermer</button> #}
			</div>

		</div>
	</main>
{% endblock %}

templates/_partials/_services.html.twig
{% if services %}
	<div class="cards-container">
		{% for service in services %}
			<div class="card card-services">
				<div class="icone-service">
					{% if service.icone %}
						<i class="{{service.icone}}"></i>
					{% endif %}
				</div>
				<p class="card-title">{{service.nom}}</p>
				<p class="card-text">{{service.resume|u.truncate(60)}}
					<a class="card-view-link" href="{{path('app_services_fiche_service',{id:service.id,slug:service.slug})}}">Voir détails...</a>
				</p>
				<p class="card-price">A partir de
					{{service.prixapartirde}}
					€</p>

				<p class="contact-service-par-mail">
				<i class="fa-regular fa-paper-plane"></i>
					<a href="{{path('app_contact_par_mail_envoyer_mail',{id:service.id,slug:service.slug})}}">Contacter par mail</a>
				</p>
				<p class="contact-service-par-telephone">
				<i class="fa-solid fa-phone"></i>
					Tel :
					<a href="tel:{{service.telephone1}}"></a>{{service.telephone1}}</p>
			</div>
		{% endfor %}
	</div>
{% else %}
	<p>Aucun service n'est encore enregistré dans la base.</p>
{% endif %}