src/Entity/Services.php
<?php

namespace App\Entity;

use App\Repository\ServicesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: ServicesRepository::class)]
#[UniqueEntity('nom',"Il existe déjà un service portant ce nom dans la base, veuillez rectifier le nom svp.")]    

class Services
{ 
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT, nullable: false)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?float $prix_a_partir_de = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $icone = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    private ?string $resume = null;

    #[ORM\OneToMany(mappedBy: 'service', targetEntity: Telephones::class)]
    private Collection $telephones;

    #[ORM\OneToMany(mappedBy: 'service', targetEntity: Mails::class)]
    private Collection $mails;

    #[ORM\Column(length: 16, nullable: true)]
    private ?string $telephone_1 = null;

    #[ORM\Column(length: 16, nullable: true)]
    private ?string $telephone_2 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $responsable = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $mail_service_1 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $mail_service_2 = null;

    #[ORM\Column]
    private ?bool $afficher = null;

    #[ORM\Column(length: 15, nullable: true)]
    private ?string $civilite_responsable = null;

    public function __toString()
    {
        return $this->nom;
    }

    public function __construct()
    {
        $this->telephones = new ArrayCollection();
        $this->mails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrixAPartirDe(): ?float
    {
        return $this->prix_a_partir_de;
    }

    public function setPrixAPartirDe(?float $prix_a_partir_de): self
    {
        $this->prix_a_partir_de = $prix_a_partir_de;

        return $this;
    }

    public function getIcone(): ?string
    {
        return $this->icone;
    }

    public function setIcone(?string $icone): self
    {
        $this->icone = $icone;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(string $resume): self
    {
        $this->resume = $resume;

        return $this;
    }

    /**
     * @return Collection<int, Telephones>
     */
    public function getTelephones(): Collection
    {
        return $this->telephones;
    }

    public function addTelephone(Telephones $telephone): self
    {
        if (!$this->telephones->contains($telephone)) {
            $this->telephones->add($telephone);
            $telephone->setService($this);
        }

        return $this;
    }

    public function removeTelephone(Telephones $telephone): self
    {
        if ($this->telephones->removeElement($telephone)) {
            // set the owning side to null (unless already changed)
            if ($telephone->getService() === $this) {
                $telephone->setService(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Mails>
     */
    public function getMails(): Collection
    {
        return $this->mails;
    }

    public function addMail(Mails $mail): self
    {
        if (!$this->mails->contains($mail)) {
            $this->mails->add($mail);
            $mail->setService($this);
        }

        return $this;
    }

    public function removeMail(Mails $mail): self
    {
        if ($this->mails->removeElement($mail)) {
            // set the owning side to null (unless already changed)
            if ($mail->getService() === $this) {
                $mail->setService(null);
            }
        }

        return $this;
    }

    public function getTelephone1(): ?string
    {
        return $this->telephone_1;
    }

    public function setTelephone1(?string $telephone_1): self
    {
        $this->telephone_1 = $telephone_1;

        return $this;
    }

    public function getTelephone2(): ?string
    {
        return $this->telephone_2;
    }

    public function setTelephone2(?string $telephone_2): self
    {
        $this->telephone_2 = $telephone_2;

        return $this;
    }

    public function getResponsable(): ?string
    {
        return $this->responsable;
    }

    public function setResponsable(?string $responsable): self
    {
        $this->responsable = $responsable;

        return $this;
    }

    public function getMailService1(): ?string
    {
        return $this->mail_service_1;
    }

    public function setMailService1(?string $mail_service_1): self
    {
        $this->mail_service_1 = $mail_service_1;

        return $this;
    }

    public function getMailService2(): ?string
    {
        return $this->mail_service_2;
    }

    public function setMailService2(?string $mail_service_2): self
    {
        $this->mail_service_2 = $mail_service_2;

        return $this;
    }

    public function isAfficher(): ?bool
    {
        return $this->afficher;
    }

    public function setAfficher(bool $afficher): self
    {
        $this->afficher = $afficher;

        return $this;
    }

    public function getCiviliteResponsable(): ?string
    {
        return $this->civilite_responsable;
    }

    public function setCiviliteResponsable(?string $civilite_responsable): self
    {
        $this->civilite_responsable = $civilite_responsable;

        return $this;
    }
}

src/Controller/Admin/ServicesController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Services;
use App\Form\ServicesFormType;
use App\Repository\ServicesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;


class ServicesController extends AbstractController
{
    public function __construct(private SluggerInterface $slugger)
    {
    }

    #[Route('/services/index', name: 'app_services_index')]
    public function index(ServicesRepository $servicesRepository): Response
    {
        $services = $servicesRepository->findBy(['afficher'=>true], ['nom' => 'ASC']);

        return $this->render('services/index.html.twig', [
            'services' => $services
        ]);
    }
    #[Route('/admin/liste-services', name: 'liste_services')]
    public function liste(ServicesRepository $servicesRepository): Response
    {
        $services = $servicesRepository->findBy([], ['nom' => 'ASC']);

        return $this->render('services/liste-services.html.twig', [
            'services' => $services
        ]);
    }

    //Créer un service
    #[Route('admin/services/creer-service', name: 'app_services_creer_service')]
    public function creer(EntityManagerInterface $em, Request $request): Response
    {

        $service = new Services();

        $form = $this->createForm(ServicesFormType::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $service->setSlug($this->slugger->slug($form->get('nom')->getdata())->lower());
            $em->persist($service);
            $em->flush();

            $this->addFlash('message', 'Le nouveau service a bien été enregistré dans la base.');
            return $this->redirectToRoute('app_services_index');
        }

        return $this->render('services/servicesForm.html.twig', [
            'servicesForm' => $form->createView(),
            'titre' => 'Créer un nouveau service'
        ]);
    }

    #[Route('/admin/services/modifier-service/{slug}/{id}', name: 'app_services_modifier_service')]
    public function modifier(Request $request, ServicesRepository $servicesRepository, $id, $slug, EntityManagerInterface $em): Response
    {
        $service = $servicesRepository->find($id);
        $slug = $service->getSlug();

        $form = $this->createForm(ServicesFormType::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $service->setSlug($this->slugger->slug($form->get('nom')->getdata())->lower());
            $em->persist($service);
            $em->flush();

            $this->addFlash('message', 'Le nouveau service a bien été modifié dans la base.');
            return $this->redirectToRoute('app_services_liste_services');
        }

        return $this->render('services/servicesForm.html.twig', [
            'servicesForm' => $form->createView(),
            'titre' => 'Modifier un service'
        ]);
    }
    #[Route('/admin/services/supprimer-service/{slug}/{id}', name: 'app_services_supprimer_service')]
    public function supprimer(ServicesRepository $servicesRepository, $id, $slug, EntityManagerInterface $em): Response
    {
        $service = $servicesRepository->find($id);
        $slug = $service->getSlug();
        $em->remove($service);
        $em->flush();
        $this->addFlash('success', 'Le service ' . $slug . ' a bien été supprimé de la base.');
        return $this->redirectToRoute('liste_services');
    }
    #[Route('/services/fiche-service/{slug}/{id}', name: 'app_services_fiche_service')]
    public function fiche(ServicesRepository $servicesRepository, $id, $slug): Response
    {
        $service = $servicesRepository->find($id);
        $slug = $service->getSlug();

        return $this->render('services/fiche.html.twig', [
            'service' => $service
        ]);
    }

    #[Route('/admin/services/afficher-service/{id}', name: 'afficher_service')]
    public function afficherService(Services $service, EntityManagerInterface $em, $id): Response
    {
        //Active ou désactive le champ de publication dans la base   
        $service->setAfficher(($service->isAfficher()) ? false : true);

        $em->persist($service);
        $em->flush();

        if (!$service->isAfficher()) {
            $this->addFlash('success', "Votre choix a été pris en compte : ce service ne sera pas affiché dans la liste des services.");

            return new Response('true');
        } else {
            $this->addFlash('success', 'Votre choix a été pris en compte : ce service ne sera dorénavant affiché dans la liste des services.');
            return new Response("false");
        }
    }
}

templates/services/fiche.html.twig
{% extends 'base.html.twig' %}
{% block title %}Fiche service
{% endblock %}
{% block body %}
	<main class="main">
		<div class="content">
			<a href="{{path('app_index')}}" class="btn btn-go-back">Retour à la page d'accueil</a>

			<h1 class="titre-principal">Fiche service
				{{service.nom}}</h1>

			<a href="{{path('app_contact_par_mail_envoyer_mail',{id:service.id,slug:service.slug})}}" class="btn btn-primary btn-centered">Contacter ce service par mail</a>
			{% if service %}
				<table
					class="fiche-service">
					{# {% if service.icone %}
																																								<p>{{service.icone}}</p>
																																							{% endif %} #}
					<thead>
						<tr>
							{% if is_granted("ROLE_ADMIN") %}
							<th colspan="2"><a href="{{path('app_services_creer_service')}}" class="btn btn-primary">Créer un service</a></th>	

							{% endif %}
						</tr>
					</thead>
					<tr>
						<td class="table-label">Résumé :</td>
						<td>
							<p>
								{{service.resume}}</p>
						</td>
					</tr>
					<tr>
						<td class="table-label">Description :</td>
						<td>
							<p>
								{{service.description}}</p>
						</td>
					</tr>
					<tr>
						<td class="table-label">Prix (à partir de : )</td>
						<td>
							<p>{{service.prixapartirde}}
								€.</p>
						</td>
					</tr>
					<tr>
						<td class="table-label">Responsable</td>
						<td>
							<p>{{service.civiliteresponsable}}
								{{service.responsable}}</p>
						</td>
					</tr>
					<tr>
						<td class="table-label">Mail service 1</td>
						<td>
							<p>{{service.mailservice1}}</p>
						</td>
					</tr>
					<tr>
						<td class="table-label">Mail service 2</td>
						<td>
							<p>{{service.mailservice2}}</p>
						</td>
					</tr>
					<tr>
						<td class="table-label">Télephone service 1</td>
						<td>
							<p>{{service.telephone1}}</p>
						</td>
					</tr>
					<tr>
						<td class="table-label">Télephone service 2</td>
						<td>
							<p>{{service.telephone2}}</p>
						</td>
					</tr>
				</table>
			{% else %}
				<p>Aucun service n'est encore enregistré dans la base</p>
			{% endif %}
		</div>
	</main>
{% endblock %}

templates/services/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<main>
<section class="services">
<h1 class="titre-principal"><i class="fa-solid fa-screwdriver-wrench"></i>Nos services</h1>
</section>
<div class="wrapper">
    {{ include('_partials/_services.html.twig') }}
</div>

</main>
    
{% endblock %}

templates/services/liste-services.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Administration des services
{% endblock %}

{% block body %}
	<main>
		<h1 class="titre-principal">Liste des services</h1>
		<div class="wrapper">
			{{ include('_partials/_admin-nav.html.twig') }}

			{% if services is not null %}
				<table class="listing">
					<thead>
						<th>Icone</th>
						<th>Nom service</th>
						<th>Résumé</th>
						<th>Prix à partir de</th>
						<th>Afficher</th>
						<th colspan="4">
							<a href="{{path('app_services_creer_service')}}" class="btn btn-primary">Créer un nouveau service</a>
						</th>
					</thead>

					<tbody>
						{% for service in services %}
							<tr>
								{% if service.icone is not null %}
									<td>
										<i class="{{service.icone}}"></i>
									</td>
								{% endif %}							

								<td>
									<strong>{{service.nom}}</strong>
								</td>
								<td>{{service.resume|u.truncate(20)}}</td>

								<td class="price">{{service.prixapartirde}}
									€</td>
								<td>
								{# switch affichage du service #}
								<td>
									<label class="switch">
										<input class="toggle-switch-afficher" type="checkbox" id="switch{{service.id}}" value="{{service.afficher}}" {{service.afficher ==1 ? "checked":""}} role="switch" data-id={{service.id}}>
										<span class="slider round"></span>
									</label>
								</td>
								<td>
									<a class="btn btn-warning" href="{{path('app_services_fiche_service',{id:service.id,slug:service.slug})}}">voir</a>
								</td>
								<td>
									<a class="btn btn-primary" href="{{path('app_services_modifier_service',{id:service.id,slug:service.slug})}}">modifier</a>
								</td>
								<td>
									<a class="btn btn-danger" href="{{path('app_services_supprimer_service',{id:service.id,slug:service.slug})}}">supprimer</a>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				{% endif %}
			</table>
		</div>
	</main>
{% endblock %}
{% block javascripts %}
	<script src="{{asset('assets/js/services.js')}}" defer></script>
{% endblock %}

templates/services/servicesForm.html.twig
{% extends 'base.html.twig' %}
{% block title %}
	{{titre}}
{% endblock %}
{% block body %}
	<main class="main">
		<div class="wrapper">
			{{ include('_partials/_admin-nav.html.twig') }}
			{{ form_start(servicesForm) }}
			<h1 class="form-header">{{titre}}</h1>
			{{ form(servicesForm) }}
				{{ form_end(servicesForm) }}
			</div>
		</main>
	{% endblock %}